name: BP Calculator

env:
  AZURE_WEBAPP_NAME: bpcalculator           
  AZURE_WEBAPP_PACKAGE_PATH: 'publish' 

on:
  push:
    branches: [ master ]

jobs:
   build_unit_test:                                        
    runs-on: windows-latest            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Build for Release
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test BPMUnitTest/BPMUnitTest.csproj --no-restore --collect "Code coverage" -l:trx
   
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
        artifact: ''
        name: MS Tests                  
        path: '**.trx'
        reporter: 'dotnet-trx'                     

    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 

# Deploy to Azure Web apps
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}                        # your app name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'


