name: BP Calculator

on:
  push:
    branches: [ master ]

jobs:
  build_unit_test:                                       
    name: build and unit test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build for Release
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test BPMUnitTest/BPMUnitTest.csproj --collect "Code coverage" 
  
  deploy_test_blue_green:                                             
    name: deploy to staging slot, run E2E tests, swap slots
    needs: build_unit_test
    environment:
      name: QA
      url: https://bpcalculator20211123205548.azurewebsites.net                                 
    runs-on: windows-latest
    env:
      AZURE_WEBAPP_NAME: BPCalculator20211123205548
      AZURE_WEBAPP_PACKAGE_PATH: '.'
    steps:
    - uses: actions/checkout@v2

# publish web app ready for deployment
    - name: Publish web app
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
    
# Deploy to Azure app service to staging slot using publish profile for staging slot
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}                            
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE  }} 
        slot-name: production
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        
# Run Selenium tests
    - name: Run Selenium tests
      run: dotnet test ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp/SeleniumTest.dll /Settings:SeleniumTest.runsettings --logger:"trx;LogFileName=selenium.trx"
      
# Upload results of selenium tests
    - uses: actions/upload-artifact@v2
      with:
        name: Selenium Tests Results
        path: TestResults/selenium.trx
      
      

        


